name: Lint Helm Charts

on:
  pull_request:
    branches:
      - master
    paths:
      - "helm/provisioner/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set-up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Set-up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.x"

      - name: Set-up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=helm --charts=helm/provisioner --lint-conf=helm/lintconf.yaml --check-version-increment=false --validate-maintainers=false

      - name: Create Kind cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced

      - name: Run chart-testing (install)
        run: ct install --chart-dirs=helm --charts=helm/provisioner
